In [27]:
import numpy as np
import pandas as pd
import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Convolution2D
from keras.layers.convolutional import MaxPooling2D
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from keras import backend as K

In [28]:
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [29]:
train_d = pd.read_csv("/content/gdrive/MyDrive/train (1).csv")

In [30]:
test_d = pd.read_csv("/content/gdrive/MyDrive/test.csv")


ML MODELS

In [31]:
#KNN with minmax scaling

import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler,MinMaxScaler


train = pd.read_csv('/content/gdrive/MyDrive/train (1).csv')
test = pd.read_csv('/content/gdrive/MyDrive/test.csv')


X_train = train.drop('labels', axis=1)


y_train = train['labels']

X_test=test.drop('id', axis=1)


scaler = MinMaxScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)




In [32]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train_s, y_train)


predictions = knn.predict(X_test_s)

predictions


array([1, 0, 0, ..., 1, 0, 1])

In [33]:
#KNN without feature selection
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler


train = pd.read_csv('/content/gdrive/MyDrive/train (1).csv')
test = pd.read_csv('/content/gdrive/MyDrive/test.csv')


X_train = train.drop('labels', axis=1)
y_train = train['labels']

X_test=test.drop('id', axis=1)


scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)





In [34]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_s, y_train)


prediction_knn = knn.predict(X_test_s)

prediction_knn

array([1, 0, 0, ..., 1, 0, 1])

In [35]:
#KNN with feature selection
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.feature_selection import SelectKBest, f_classif
from sklearn.preprocessing import StandardScaler


train = pd.read_csv('/content/gdrive/MyDrive/train (1).csv')
test = pd.read_csv('/content/gdrive/MyDrive/test.csv')


X_train = train.drop('labels', axis=1)
y_train = train['labels']

X_test=test.drop('id', axis=1)

n_f = 900
selector = SelectKBest(score_func=f_classif, k=n_f)
X_train_selected = selector.fit_transform(X_train, y_train)


scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train_selected)
X_test_s = scaler.transform(selector.transform(X_test))





In [36]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_s, y_train)


predictions_knn_f = knn.predict(X_test_s)

predictions_knn_f

array([1, 0, 0, ..., 1, 0, 1])

In [37]:
#Random forest
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler


train = pd.read_csv('/content/gdrive/MyDrive/train (1).csv')
test = pd.read_csv('/content/gdrive/MyDrive/test.csv')


X_train = train.drop('labels', axis=1)
y_train = train['labels']
X_test= test.drop('id', axis=1)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)









In [38]:
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)

rf_classifier.fit(X_train_s, y_train)


prediction_rf = rf_classifier.predict(X_test_s)

prediction_rf

array([0, 0, 0, ..., 1, 0, 0])

In [39]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(predictions_knn_f, prediction_rf)
print("Accuracy:", accuracy)

Accuracy: 0.8524444444444444


In [40]:
solution = pd.DataFrame(predictions_knn_f,columns=['labels'])
solution['id']=0;
for i in range(len(solution)):
    solution.at[i, 'id'] = i + 1

solution= solution.rename(columns={'labels': 'id', 'id': 'labels'})
solution['labels'], solution['id'] = solution['id'], solution['labels']
solution

id  labels
0        1       1
1        2       0
2        3       0
3        4       0
4        5       0
...    ...     ...
2245  2246       0
2246  2247       0
2247  2248       1
2248  2249       0
2249  2250       1

[2250 rows x 2 columns]

In [41]:
solution.to_csv('solutionknn_feature_830.csv', index=False)